name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Publish Docker Images to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta_api
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: chabbay/voteaquote_api

    - name: Extract metadata (tags, labels) for Docker
      id: meta_angular
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: chabbay/voteaquote_angular
    
    - name: Build and push API Docker Image
      id: push_api
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: ./API
        file: ./API/Dockerfile
        push: true
        tags: chabbay/voteaquote_api:latest
        labels: ${{ steps.meta.outputs.labels }}

    - name: Build and push Angular Docker Image
      id: push_angular
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: ./Angular
        file: ./Angular/Dockerfile
        push: true
        tags: chabbay/voteaquote_angular:latest
        labels: ${{ steps.meta.outputs.labels }}

    - name: Generate artifact attestation for API
      uses: actions/attest-build-provenance@v1
      with:
        subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
        subject-digest: ${{ steps.push_api.outputs.digest }}
        push-to-registry: true

    - name: Generate artifact attestation for Angular
      uses: actions/attest-build-provenance@v1
      with:
        subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
        subject-digest: ${{ steps.push_angular.outputs.digest }}
        push-to-registry: true
